---
- hosts: win
  vars:
    name: David
  tasks:
    - name: Copy html file
      win_template:
        src: webpage.html.j2
        dest: "C:\\inetpub\\wwwroot\\webpage.html"
      notify: restart iis
  handlers:
    - name: restart iis
      win_shell: '& {iisreset}' 
