---
- hosts: win
  tasks:
    - name: updating firewall rule
      win_firewall_rule:
        name: Rule By Ansible
        localport: 8080
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes
    - name: updating firewall out rule
      win_firewall_rule:
        name: Rule Out By Ansible
        localport: 8080
        action: allow
        direction: out
        protocol: tcp
        state: present
        enabled: yes
