---
- hosts: web
  tasks:
    - name: apt update
      apt:
        update_cache: true
    - name: package installation - supported
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: add key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: Add Repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: apt update2
      apt:
        update_cache: true
    - name: docker installation
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
