---
- hosts: web
  tasks:
    - name: Copying a file
      copy:
        src: script.sh
        dest: /home/ubuntu/
      notify: restart docker
    - name: Copying with Template
      template:
        src: testfile.txt.j2
        dest: /home/ubuntu/testfile.txt
      notify: restart ntp
    - name: Creating a directory
      file:
        path: /home/ubuntu/somedir
        state: directory
  handlers:
    - name: restart ntp
      service:
        name: ntp
        state: restarted
    - name: restart docker
      service:
        name: docker
        state: restarted
