---
- hosts: web
  tasks:
    - name: installing prereq
      apt:
        name:
          - default-jdk
          - wget
    - name: ensure directory
      file:
        path: /opt/tomcat/
        state: directory
    - name: download tomcat tar
      get_url:
        url: http://mirror.23media.de/apache/tomcat/tomcat-8/v8.5.29/bin/apache-tomcat-8.5.29.tar.gz 
        dest: /opt/tomcat
    - name: extracting
      unarchive:
        src: /opt/tomcat/apache-tomcat-8.5.29.tar.gz
        dest: /opt/tomcat
        remote_src: yes
    - name: permissions
      shell: cd /opt/tomcat/apache-tomcat-8.5.29/bin && chmod 777 startup.sh shutdown.sh catalina.sh
    - name: get sample
      get_url:
        url: https://tomcat.apache.org/tomcat-8.0-doc/appdev/sample/sample.war
        dest: /opt/tomcat/apache-tomcat-8.5.29/webapps/
    - name: sleep
      pause:
        minutes: 1
    - name: starting tomcat
      shell: /opt/tomcat/apache-tomcat-8.5.29/bin/catalina.sh start
      register: output
    - debug: 
        var: output.stdout


