---
- name: install "{{ todo }}"  
  apt:
    name: "{{ todo }}"
    state: present
- name: moving a file
  template:
    src: somefile.txt.j2
    dest: /home/ubuntu/{{ todo }}.txt
  notify: restart ntp
